import type {Metadata} from "next";
import {SiteHeader} from "../components/SiteChrome";
import PublicationExplorer from "./PublicationExplorer";

export const metadata:Metadata={title:"Battery, Membrane & MOF Publications",description:"Peer-reviewed battery, electrolyte, membrane, MOF, and electrocatalysis publications by chemical engineering researcher Mehran Arzani.",alternates:{canonical:"/publications"}};

const publications=[
 {year:"2026",topic:"Electrocatalysis",journal:"ACS Applied Materials & Interfaces",title:"Intrinsically Conductive π-d Conjugated Layers with Co-N₄ Active Sites for Efficient Nitrate Electrocatalysis and Zinc-Nitrate Batteries",url:"https://pubs.acs.org/doi/10.1021/acsami.6c00231"},
 {year:"2025",topic:"Energy",journal:"ACS Energy Letters",title:"Engineering Porous Liquids for Enhanced Ion Mobility and Stable Battery Electrolytes",url:"https://pubs.acs.org/doi/10.1021/acsenergylett.5c01446"},
 {year:"2025",topic:"MOFs",journal:"Advanced Materials",title:"Practical Considerations in the Design and Use of Non-Crystalline Metal-Organic Frameworks",url:"https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/adma.202505579"},
 {year:"2023",topic:"Membranes",journal:"Industrial & Engineering Chemistry Research",title:"An Overview of Practical Aspects of the Design and Application of Polymeric/Ceramic Supports in Supported Liquid Membranes for Gas Separation",url:"https://pubs.acs.org/doi/10.1021/acs.iecr.3c00830"},
 {year:"2023",topic:"Membranes",journal:"Journal of Industrial and Engineering Chemistry",title:"Stabilization of [BMIM][PF₆] Ionic Liquid Membrane in Structurally Optimized Multilayer Ceramic Support through Aqueous DEA Solution for CO₂/CH₄ Separation",url:"https://www.sciencedirect.com/science/article/pii/S1226086X23004069"},
 {year:"2023",topic:"Membranes",journal:"Materials Today Communications",title:"Enhancing CO₂ Permeation Features of PEBAX-Based Membrane via Incorporating MgO Nanoparticles in Its Polymeric Matrix",url:"https://www.sciencedirect.com/science/article/pii/S2352492823001502"},
 {year:"2019",topic:"Membranes",journal:"Ceramics International",title:"Kaolinitic Clay-Based Ceramic Microfiltration Membrane for Oily Wastewater Treatment: Assessment of Coagulant Addition",url:"https://www.sciencedirect.com/science/article/pii/S0272884219314816"},
 {year:"2018",topic:"Membranes",journal:"Journal of Environmental Management",title:"Effect of Hydrophobic and Hydrophilic Nanoparticles Loaded in D2EHPA/M2EHPA-PTFE Supported Liquid Membrane for Simultaneous Cationic Dyes Pertraction",url:"https://www.sciencedirect.com/science/article/pii/S0301479718301786"},
 {year:"2018",topic:"Membranes",journal:"Ceramics International",title:"Synthesis, Characterization and Performance Evaluation of an Optimized Ceramic Membrane with Physical Separation and Photocatalytic Degradation Capabilities",url:"https://www.sciencedirect.com/science/article/pii/S0272884218305893"},
 {year:"2018",topic:"Membranes",journal:"Applied Clay Science",title:"Ceramic Monolith as Microfiltration Membrane: Preparation, Characterization and Performance Evaluation",url:"https://www.sciencedirect.com/science/article/pii/S0169131718302345"},
 {year:"2018",topic:"Membranes",journal:"Journal of Oil, Gas and Petrochemical Technology",title:"Performance Evaluation of Mullite Ceramic Membrane for Oily Wastewater Treatment Using Response Surface Methodology Based on Box-Behnken Design",url:"https://jogpt.pgu.ac.ir/article_85637.html"},
 {year:"2017",topic:"MOFs",journal:"Journal of Molecular Liquids",title:"Novel Amine Modification of ZIF-8 for Improving Simultaneous Removal of Cationic Dyes from Aqueous Solutions Using Supported Liquid Membrane",url:"https://www.sciencedirect.com/science/article/pii/S0167732216322462"},
 {year:"2017",topic:"Membranes",journal:"Korean Journal of Chemical Engineering",title:"Synthesis and Characterization of Poly(ether-block-amide) Copolymers/Multi-Walled Carbon Nanotube Nanocomposite Membranes for CO₂/CH₄ Separation",url:"https://link.springer.com/article/10.1007/s11814-017-0152-8"},
 {year:"2017",topic:"Membranes",journal:"Journal of Natural Gas Science and Engineering",title:"Improved CO₂/CH₄ Separation Using a Nanocomposite Ionic Liquid Gel Membrane",url:"https://www.sciencedirect.com/science/article/pii/S1875510017303219"},
 {year:"2016",topic:"Membranes",journal:"Ceramics International",title:"Preparation of Mullite Ceramic Microfilter Membranes Using Response Surface Methodology Based on Central Composite Design",url:"https://www.sciencedirect.com/science/article/pii/S0272884216002832"},
 {year:"2016",topic:"Membranes",journal:"Chemical Engineering and Processing",title:"Pertraction of L-Lysine by Supported Liquid Membrane Using D2EHPA/M2EHPA",url:"https://www.sciencedirect.com/science/article/pii/S0255270116301088"},
 {year:"2025",topic:"Energy",journal:"ECS Meeting Abstracts 248 · Conference Paper",title:"Contribution of Porous Liquids for Enhanced Battery Electrolyte Stability and Mobility",url:"https://iopscience.iop.org/article/10.1149/MA2025-02136mtgabs"},
 {year:"2024",topic:"Energy",journal:"AIChE Annual Meeting · Conference Paper",title:"Unveiling the Potential of Porous Liquid-Based Electrolytes in Battery Applications: Improved Conductivity and Ion Mobility in Lithium and Sodium-Based Batteries",url:"https://aiche.confex.com/aiche/2024/meetingapp.cgi/Paper/693388"},
 {year:"2024",topic:"Energy",journal:"AIChE Annual Meeting · Conference Paper",title:"Lithium-Sulfur Battery Performance Enhancement through the Integration of Porous Liquid-Based Electrolytes: Insights into Improved Ion Mobility and Ionic Conductivity",url:"https://aiche.confex.com/aiche/2024/prelim.cgi/Paper/693194"},
 {year:"2024",topic:"Energy",journal:"ECS Meeting Abstracts 245 · Conference Paper",title:"Modified Liquid Electrolyte with Porous Liquid Type-II for Lithium-Metal Batteries",url:"https://iopscience.iop.org/article/10.1149/MA2024-01196mtgabs/meta"}
];
const journalShowcase=[publications[0],publications[1],publications[2],publications[3],publications[5],publications[6],publications[7],publications[9],publications[12],publications[15]];
export default function Publications(){return <main className="publications-page" id="top">
  <SiteHeader active="Publications"/>
  <section className="publication-hero section"><div><p className="section-kicker">RESEARCH OUTPUT</p><h1><span className="publication-hero-icon" aria-hidden="true">▤</span> Publications</h1><p>Peer-reviewed articles and conference papers spanning energy storage, advanced electrolytes, membranes, and molecular transport.</p></div><dl className="publication-impact"><div><dt>20</dt><dd>Research outputs</dd></div><div><dt>500+</dt><dd>Citations</dd></div></dl></section>
  <section className="journal-carousel-section section" aria-labelledby="journal-showcase-title">
    <header className="journal-carousel-heading"><p className="section-kicker">SELECTED PUBLICATIONS</p><h2 id="journal-showcase-title">Journals</h2></header>
    <div className="journal-carousel-frame" aria-label="Rotating three-dimensional gallery of journals featuring Mehran Arzani's publications">
      <div className="journal-carousel-ring">{journalShowcase.map((p,i)=><a className={`journal-cover-card journal-cover-${i+1}`} href={p.url} target="_blank" rel="noreferrer" key={p.journal}><span>{p.year}</span><strong>{p.journal}</strong><p>{p.topic}</p><b>View paper ↗</b></a>)}</div>
      <div className="journal-carousel-halo" aria-hidden="true"/>
    </div>
  </section>
  <section className="featured-publications section" aria-labelledby="featured-title"><div className="featured-heading"><p className="section-kicker">SELECTED WORK</p><h2 id="featured-title">Featured publications</h2></div><div className="featured-publication-grid">{publications.slice(0,3).map((p,i)=><a href={p.url} target="_blank" rel="noreferrer" key={p.title}><span>0{i+1} · {p.topic}</span><h3>{p.title}</h3><p>{p.journal} · {p.year}</p><b>Read paper ↗</b></a>)}</div></section>
  <section className="research-evolution section" aria-labelledby="evolution-title"><div><p className="section-kicker">RESEARCH EVOLUTION</p><h2 id="evolution-title">Materials to energy systems</h2></div><ol><li><time>2016–2019</time><strong>Membranes</strong><span>Microfiltration and drinking water as an urgent need in response to water scarcity; gas separation and greenhouse-gas removal for cleaner air and climate protection.</span></li><li><time>2017–2023</time><strong>Membranes &amp; Materials</strong><span>Polymeric materials, nanoparticles, and nanocomposite membranes.</span></li><li><time>2025–2026</time><strong>Energy Storage</strong><span>Batteries, electrolytes, cathodes, and anodes for a sustainable future.</span></li></ol></section>
  <PublicationExplorer publications={publications}/>
  <footer><span>© 2026 Mehran Arzani</span><a href="/">← Back to home</a><a href="#top">Back to top ↑</a></footer>
</main>}
