import {PageFooter,PageHero,SiteHeader} from "../components/SiteChrome";
import {pageMetadata} from "../seo";

export const metadata=pageMetadata("Battery & Electrolyte Conference Presentations","Conference abstracts and presentations by Mehran Arzani on battery electrolytes, porous liquids, ion transport, lithium–oxygen batteries, and energy storage.","/conferences");

const talks=[
  {year:"2025",event:"Electrochemical Society Meeting Abstracts 248",format:"Conference abstract",title:"Contribution of Porous Liquids for Enhanced Battery Electrolyte Stability and Mobility",url:"https://iopscience.iop.org/article/10.1149/MA2025-02136mtgabs"},
  {year:"2024",event:"2024 AIChE Annual Meeting",format:"Conference presentation",title:"Unveiling the Potential of Porous Liquid-Based Electrolytes in Battery Applications: Improved Conductivity and Ion Mobility in Lithium and Sodium-Based Batteries",url:"https://aiche.confex.com/aiche/2024/meetingapp.cgi/Paper/693388"},
  {year:"2024",event:"2024 AIChE Annual Meeting",format:"Conference presentation",title:"Lithium-Sulfur Battery Performance Enhancement through the Integration of Porous Liquid-Based Electrolytes: Insights into Improved Ion Mobility and Ionic Conductivity",url:"https://aiche.confex.com/aiche/2024/prelim.cgi/Paper/693194"},
  {year:"2024",event:"Electrochemical Society Meeting Abstracts 245",format:"Conference abstract",title:"Modified Liquid Electrolyte with Porous Liquid Type-II for Lithium-Metal Batteries",url:"https://iopscience.iop.org/article/10.1149/MA2024-01196mtgabs/meta"},
];

export default function Conferences(){return <main className="profile-subpage conference-page" id="top">
  <SiteHeader active="Conferences"/>
  <PageHero kicker="SCIENTIFIC COMMUNICATION" title="Conferences" icon="◎" description="Conference contributions advancing porous-liquid electrolytes, ion transport, and next-generation battery systems." metric="4" metricLabel="featured contributions"/>
  <section className="conference-stage-section section" aria-labelledby="conference-stage-title"><div className="conference-stage-heading"><p className="section-kicker">RESEARCH PRESENTATION STAGE</p><h2 id="conference-stage-title">Ideas presented to the scientific community</h2></div><div className="conference-stage"><div className="stage-spotlight" aria-hidden="true"/><div className="presentation-screen">{talks.map((talk,i)=><a className={`presentation-slide presentation-slide-${i+1}`} href={talk.url} target="_blank" rel="noreferrer" key={talk.title}><span>{talk.event} · {talk.year}</span><h3>{talk.title}</h3><b>{talk.format} · View abstract ↗</b><i aria-hidden="true"/></a>)}</div><div className="conference-podium" aria-hidden="true"><span>MA</span></div><div className="conference-stage-badges"><span>ECS 245</span><span>AIChE 2024</span><span>ECS 248</span></div><div className="stage-floor" aria-hidden="true"/></div></section>
  <section className="conference-gallery section" aria-labelledby="conference-gallery-title">
    <div className="conference-gallery-heading"><p className="section-kicker">PRESENTING THE RESEARCH</p><h2 id="conference-gallery-title">Ideas in conversation</h2></div>
    <div className="conference-photos"><figure><img src="/conference-presentation-ecs.png" alt="Mehran Arzani presenting lithium-oxygen battery research in a conference room"/><figcaption><span>Battery research presentation</span><small>Electrochemistry · Energy storage · Advanced electrolytes</small></figcaption></figure><figure><img src="/conference-presentation-aiche.png" alt="Mehran Arzani presenting porous-liquid electrolyte research at the AIChE Annual Meeting"/><figcaption><span>AIChE Annual Meeting</span><small>Porous-liquid electrolytes · Lithium-sulfur batteries</small></figcaption></figure><figure><img src="/conference-aiche-orlando-2023.png" alt="Mehran Arzani at the 2023 AIChE Annual Meeting in Orlando, Florida"/><figcaption><span>AIChE Annual Meeting · Orlando</span><small>Orlando, Florida · 2023</small></figcaption></figure></div>
  </section>
  <section className="record-section section"><div className="record-intro"><p className="section-kicker">SELECTED CONTRIBUTIONS</p><h2>Research shared with the scientific community</h2></div><div className="conference-records">{talks.map((talk,i)=><a href={talk.url} target="_blank" rel="noreferrer" key={talk.title}><span className="record-number">{String(i+1).padStart(2,"0")}</span><div><p className="record-meta">{talk.event} · {talk.year}</p><h3>{talk.title}</h3><span className="record-badge">{talk.format}</span></div><span className="conference-arrow" aria-hidden="true">↗</span></a>)}</div><aside className="profile-note"><strong>Conference support</strong><p>Recipient of three UIC conference travel awards, including support connected with the 245th and 248th ECS meetings.</p></aside></section>
  <PageFooter/>
</main>}
