import {SiteHeader} from "../components/SiteChrome";
import {pageMetadata} from "../seo";

export const metadata=pageMetadata("Research, Teaching & Engineering Awards","Awards recognizing Mehran Arzani's achievements in battery research, chemical engineering, teaching, mentorship, and academic excellence.","/awards");

const awards=[
 {year:"2013",title:"B.S. Chemical Engineering · First Rank / Top 1%",org:"Azad University · Esfahan",category:"Academic Excellence",links:[]},
 {year:"2024–25",title:"Three Conference Travel Awards",org:"University of Illinois Chicago · The Electrochemical Society",category:"Research Communication",links:[]},
 {year:"2025",title:"Chicago Consular Corps Award",org:"Office of Global Engagement · University of Illinois Chicago",category:"Professional Development",links:[{label:"Read the UIC news story",url:"https://che.uic.edu/news-stories/grad-student-receives-chicago-consular-corps-professional-development-award/"}]},
 {year:"2025",title:"Tau Beta Pi Engineering Honor Society · Top 5%",org:"University of Illinois Chicago",category:"Academic Excellence",links:[{label:"View the LinkedIn post",url:"https://www.linkedin.com/posts/mehran-arzani-b9228624b_last-friday-i-had-the-honor-of-being-inducted-activity-7403921248323395584-M5FD?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD3Mfx4Bv2_m_vaWLc4N76NtAXZCPOq7HoI"}]},
 {year:"2025",title:"Award for Graduate Research (AGR)",org:"Graduate College · University of Illinois Chicago",category:"Research",links:[{label:"Fall 2025 award recipients",url:"https://grad.uic.edu/news-stories/recipients-of-fall-2025-awards/"},{label:"Chemical Engineering student awards",url:"https://che.uic.edu/undergraduate-programs/student-resources/awards/#student-awards"}]},
 {year:"2026",title:"Graduate Student Excellence and Mentoring Award · Honorable Mention",org:"University of Illinois Chicago",category:"Mentoring",links:[{label:"Fall 2025 award recipients",url:"https://grad.uic.edu/news-stories/recipients-of-fall-2025-awards/"},{label:"Chemical Engineering student awards",url:"https://che.uic.edu/undergraduate-programs/student-resources/awards/#student-awards"}]},
 {year:"2026",title:"Excellence in Teaching Assistance",org:"College of Engineering · University of Illinois Chicago",category:"Teaching",links:[{label:"View the LinkedIn post",url:"https://www.linkedin.com/posts/mehran-arzani-b9228624b_i-am-truly-honored-to-receive-the-college-ugcPost-7458527746806190080-PxA4/?utm_source=share&utm_medium=member_desktop&rcm=ACoAAD3Mfx4Bv2_m_vaWLc4N76NtAXZCPOq7HoI"}]}
];

export default function Awards(){return <main className="awards-page" id="top">
  <SiteHeader active="Awards"/>
  <section className="award-hero section"><div><p className="section-kicker">HONORS & RECOGNITION</p><h1><span className="award-hero-icon" aria-hidden="true">✦</span> Awards</h1><p>Recognition for research, teaching, mentoring, leadership, and academic excellence.</p></div><div className="award-total"><strong>7</strong><span>distinctions</span></div></section>
  <section className="recognition-pathway section" aria-labelledby="recognition-path-title"><div className="recognition-path-heading"><p className="section-kicker">AWARD JOURNEY</p><h2 id="recognition-path-title">A timeline of growing impact</h2><p>From academic excellence to research, mentoring, and teaching recognition.</p></div><div className="recognition-stage"><div className="recognition-line" aria-hidden="true"/>{awards.map((award,i)=><article className={`recognition-milestone${i===awards.length-1?" is-latest":""}`} key={award.title}><span className="milestone-dot" aria-hidden="true"/><time>{award.year}</time><strong>{award.category}</strong><span>{award.title}</span></article>)}</div></section>
  <section className="award-gallery section" aria-labelledby="award-gallery-title"><div className="award-gallery-heading"><p className="section-kicker">AWARD MOMENTS</p><h2 id="award-gallery-title">Recognition in research, teaching, and leadership</h2></div><div className="award-photos"><figure><img src="/uic-awards-recognition-web.png" alt="UIC recognition for Mehran Arzani's graduate research and excellence in teaching and mentoring"/><figcaption><span>UIC Graduate Recognition</span><small>Award for Graduate Research · Excellence in Teaching & Mentoring</small></figcaption></figure><figure><a href="https://che.uic.edu/news-stories/grad-student-receives-chicago-consular-corps-professional-development-award/" target="_blank" rel="noreferrer" aria-label="Read about the Chicago Consular Corps Professional Development Award"><img src="/chicago-consular-corps-award-web.png" alt="Mehran Arzani receiving the Chicago Consular Corps Professional Development Award at UIC"/></a><figcaption><span>Chicago Consular Corps Professional Development Award</span></figcaption></figure></div><div className="ceremony-photos ceremony-photos-only"><figure><img src="/uic-award-group-web.png" alt="UIC award recipients and university community gathered for a group photograph"/></figure><figure><img src="/uic-award-presentation-web.png" alt="Mehran Arzani receiving recognition during a UIC award ceremony"/></figure><figure><img src="/uic-award-honorees-web.png" alt="UIC award honorees holding their recognition certificates"/></figure></div></section>
  <section className="awards section awards-catalog"><div className="award-grid">{awards.map((a,i)=><article key={a.title}><span className="award-index">{String(i+1).padStart(2,"0")}</span><time>{a.year}</time><span className="award-category">{a.category}</span><h3>{a.title}</h3><p>{a.org}</p>{a.links.length>0&&<div className="award-source-links">{a.links.map(link=><a href={link.url} target="_blank" rel="noreferrer" key={link.url}>{link.label}<span aria-hidden="true">↗</span></a>)}</div>}</article>)}</div></section>
  <footer><span>© 2026 Mehran Arzani</span><a href="/">← Back to home</a><a href="#top">Back to top ↑</a></footer>
</main>}
